//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanji2GIF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SVG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SVG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kanji2GIF.SVG", typeof(SVG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/svg&gt;.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;{0}&quot; height=&quot;109&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; xmlns:xlink=&quot;http://www.w3.org/1200/xlink&quot; xml:space=&quot;preserve&quot; version=&quot;1.1&quot; baseProfile=&quot;full&quot;&gt;.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;line x1=&quot;1&quot; y1=&quot;54.5&quot; x2=&quot;109&quot; y2=&quot;54.5&quot; stroke=&quot;#dddddd&quot; stroke-width=&quot;1&quot; /&gt;&lt;line x1=&quot;54.5&quot; y1=&quot;1&quot; x2=&quot;54.5&quot; y2=&quot;109&quot; stroke=&quot;#dddddd&quot; stroke-width=&quot;1&quot; /&gt;.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path stroke-width=&quot;2&quot; fill=&quot;none&quot; stroke=&quot;{0}&quot; stroke-dasharray=&quot;{1},{1}&quot; stroke-dashoffset=&quot;{1}&quot; d=&quot;{2}&quot;&gt;&lt;animate begin=&quot;{3}s&quot; attributeName=&quot;stroke-dashoffset&quot; from=&quot;{1}&quot; to=&quot;0&quot; dur=&quot;{4}s&quot; fill=&quot;freeze&quot; /&gt;&lt;/path&gt;.
        /// </summary>
        internal static string Stroke {
            get {
                return ResourceManager.GetString("Stroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string StrokeBasic {
            get {
                return ResourceManager.GetString("StrokeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/g&gt;.
        /// </summary>
        internal static string TransformFooter {
            get {
                return ResourceManager.GetString("TransformFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;g transform = &quot;translate({0}, 0)&quot;&gt;.
        /// </summary>
        internal static string TransformHeader {
            get {
                return ResourceManager.GetString("TransformHeader", resourceCulture);
            }
        }
    }
}
